baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo GitHub Issue #11898'

[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = 'data'
target = 'assets/data'
