baseURL = 'https://example.org/foo/'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

relativeURLs = true

[languages.en]
title = 'Hugo Forum Topic #48441 (en)'
languageName = 'English'
weight = 1

[languages.de]
title = 'Hugo Forum Topic #48441 (de)'
languageName = 'Deutsch'
weight = 2
