baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #48427'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20
