baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #48516'

disableKinds = ['rss','sitemap']
paginate = 1

[taxonomies]
tag = 'tags'
author = 'authors'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Authors'
pageRef = '/authors'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30
