baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo GitHub Issue #10893'

[module]
replacements = 'github.com/jmooring/hugo-content -> /home/jmooring/code/hugo-content'

[[module.imports]]
path = "github.com/jmooring/hugo-content"

[[module.imports.mounts]]
source = 'content/articles/article-5.md'
target = 'content/docs/a-prime.md'
