baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo GitHub Issue #10894'

[params.latex]
enabled = true
renderer = 'MathJax' # KaTeX or MathJax (case-insensitive)

# Benchmark testing
# https://www.intmath.com/cg5/katex-mathjax-comparison.php?processor=MathJax3
#
# MathJax 3 is 3x faster than KaTeX. So when people say MathJax is slower,
# that's based on MathJax 2.7, which was really slow.

[markup.goldmark.extensions.passthrough]
enable = true

# Default delimiters, but I expect this will change.
# See https://github.com/gohugoio/hugo/pull/11866#issuecomment-1904494836
#
# [markup.goldmark.extensions.passthrough.delimiters]
# block = [['$$', '$$'], ['\[', '\]']]
# inline = [['$', '$'], ['\(', '\)']]
