baseURL = 'https://example.org/'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
contentDir = 'content/en'
languageCode = 'en-US'
languageDirection = 'ltr'
languageName = 'English'
title = 'Hugo GitHub Issue #10169 (en)'
weight = 1

[languages.es]
contentDir = 'content/es'
languageCode = 'es-ES'
languageDirection = 'ltr'
languageName = 'Espanol'
title = 'Hugo GitHub Issue #10169 (es)'
weight = 2

[languages.fr]
contentDir = 'content/fr'
languageCode = 'fr-FR'
languageDirection = 'ltr'
languageName = 'Francais'
title = 'Hugo GitHub Issue #10169 (fr)'
weight = 3
