baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo GitHub Issue #10482'

[[module.mounts]]
source = 'content'
target = 'content'

[[module.mounts]]
source = 'content-gen'
target = 'content'
