baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #47779'

disableKinds = ['rss','sitemap']

[taxonomies]
tag = 'tags'

[permalinks.taxonomy]
tags = '/subject'

[permalinks.term]
tags = '/subject/:slug'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30
