baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo GitHub Issue #12107'

disableKinds = ['rss','sitemap','taxonomy','term']
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages.en]
[languages.de]
