baseURL = 'https://example.org/'
title = 'Hugo Forum Topic #48402'

disableKinds = ['taxonomy','term']

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
weight = 1

[languages.de]
weight = 2
