baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo GitHub Issue #10894'

[params.latex]
enabled = true
renderer = 'KaTeX' # KaTeX or MathJax (case-insensitve)

[markup.goldmark.extensions.passthrough]
enable = true
delimiters = [
  [ "$", "$" ],
  [ "$$", "$$" ],
  [ "\\(", "\\)" ],
  [ "\\[", "\\]" ]
]
