baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo GitHub Issue #12121'
disableKinds = ['home','rss','sitemap']
pluralizeListTitles = false
capitalizeListTitles = false

[taxonomies]
tag = 'tags'
