baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #47780'

[[module.mounts]]
source = 'content'
target = 'content'

[[module.mounts]]
source = 'prebuild/public'
target = 'content'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Pets'
pageRef = '/pets'
weight = 20
