baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #47811'

[taxonomies]
gallery = 'galleries'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Galleries'
pageRef = '/galleries'
weight = 20
