baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #48374'
disableKinds = ['home','page','rss','section','sitemap','taxonomy','term']

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'foo/dir/b.txt'
target = 'static/dir/b.txt'
