baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #48037'

defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = true

[languages.en]
# contentDir = 'content/en'
languageCode = 'en-US'
languageDirection = 'ltr'
languageName = 'English'
weight = 1

[languages.de]
# contentDir = 'content/de'
languageCode = 'de-DE'
languageDirection = 'ltr'
languageName = 'Deutsch'
weight = 2

[taxonomies]
tag = 'tags'
