baseURL = 'https://example.org/'
disableKinds = ['rss','sitemap','taxonomy', 'term']

defaultContentLanguage = 'en'
defaultContentLanguageInSubDir = true

[languages.en]
weight = 1

[languages.nn]
weight = 2
