baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo GitHub Issue #12017'
theme = 'PaperMod'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20
