baseURL = 'https://example.org/'
title = 'Hugo Forum Topic #48359'

disableKinds = ['rss','sitemap','taxonomy','term']

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
contentDir = 'content/en'
weight = 1

[languages.de]
contentDir = 'content/de'
weight = 2
